version: 2

jobs:
  web:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Restore npm dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build app
          command: npm run build
      - deploy:
          name: Deploy app
          command: npm run deploy


workflows:
  version: 2

  Build:
    jobs:
      - web
