version: '2'

services:

  web:
    container_name: web
    build:
      context: ../dist/
      dockerfile: ../deploy/web.Dockerfile
    ports:
      - '8080:80'
    networks:
      - root    

networks: 
  root:
    driver: bridge
